# Generated by Django 4.2.11 on 2024-04-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ("doctor_schedule",)},
        ),
        migrations.AlterModelOptions(
            name="doctorschedule",
            options={"ordering": ("date", "timeslot")},
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="doctors",
            new_name="doctor",
        ),
        migrations.RenameField(
            model_name="doctorschedule",
            old_name="doctors",
            new_name="doctor",
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "date", "timeslot")},
        ),
    ]
