# Generated by Django 5.0.4 on 2024-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="licence_number",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
