# Generated by Django 4.2.11 on 2024-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors_service", "0002_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorschedule",
            name="date",
            field=models.DateField(help_text="YYYY-MM-DD"),
        ),
    ]
