# Generated by Django 4.2.11 on 2024-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors_service", "0003_alter_doctorschedule_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="insurance_number",
            field=models.IntegerField(unique=True),
        ),
    ]
