# Generated by Django 4.2.11 on 2024-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors_service", "0005_alter_doctor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="insurance_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
